# "CARA INSTALL YA VROH😎"

"pkg update && pkg upgrade"
"pkg install python && pkg install python2"
"pkg install git"
"git clone https://github.com/Rezahasyim/Crack"
"ls"
"cd Crack"
"ls"
"python2 KONTOL.py"
